# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
            SOLR_COMMS: https
            TRUSTSTORE_TYPE: JCEKS
            TRUSTSTORE_PASS: kT9X6oe68t
            KEYSTORE_TYPE: JCEKS
            KEYSTORE_PASS: kT9X6oe68t
        mem_limit: 1800m
        environment:
            JAVA_OPTS: "
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.driver=org.postgresql.Driver
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port.ssl=8983
                -Dsolr.secureComms=https
                -Dsolr.base.url=/solr
                -Dsolr.useDynamicShardRegistration=true
                -Dindex.subsystem.name=solr6
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dshare.host=localhost
                -Dshare.port=8080
                -Daos.baseUrlOverwrite=https://localhost:8080/alfresco/aos
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Dmessaging.subsystem.autoStart=false
                -Dauthentication.protection.enabled=false
                -XX:+UseG1GC -XX:+UseStringDeduplication
                -Xms1500m -Xmx1500m
                "
        ports:
            - 8443:8443
        volumes:
            - ./keystores/alfresco:/usr/local/tomcat/alf_data/keystore

    solr6:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_TAG}
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: https
            TRUSTSTORE_TYPE: JCEKS
            KEYSTORE_TYPE: JCEKS
            ENABLE_SHARDING: "true"
            NUM_SHARDS: "2"
            SHARD_ID: "0"
            SHARDING_METHOD: DB_ID
        mem_limit: 1200m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8443"
            ALFRESCO_SECURE_COMMS: https
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
            SOLR_SSL_TRUST_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.truststore"
            SOLR_SSL_TRUST_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_TRUST_STORE_TYPE: "JCEKS"
            SOLR_SSL_KEY_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.keystore"
            SOLR_SSL_KEY_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_NEED_CLIENT_AUTH: "true"
            SOLR_SSL_CLIENT_KEY_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.keystore"
            SOLR_SSL_CLIENT_KEY_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_CLIENT_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_CLIENT_TRUST_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.keystore"
            SOLR_SSL_CLIENT_TRUST_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_CLIENT_TRUST_STORE_TYPE: "JCEKS"
            SOLR_OPTS: "
                -Dsolr.ssl.checkPeerName=false
                -Dsolr.allow.unsafe.resourceloading=true
            "
        ports:
            - 8083:8983
        volumes:
            - ./keystores/solr:/opt/alfresco-search-services/keystore


    solr6secondary:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_TAG}
            SOLR_HOSTNAME: solr6secondary
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: https
            TRUSTSTORE_TYPE: JCEKS
            KEYSTORE_TYPE: JCEKS
            ENABLE_SHARDING: "true"
            NUM_SHARDS: "2"
            SHARD_ID: "1"
            SHARDING_METHOD: DB_ID
        mem_limit: 1200m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8443"
            ALFRESCO_SECURE_COMMS: https
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6secondary"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
            SOLR_SSL_TRUST_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.truststore"
            SOLR_SSL_TRUST_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_TRUST_STORE_TYPE: "JCEKS"
            SOLR_SSL_KEY_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.keystore"
            SOLR_SSL_KEY_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_NEED_CLIENT_AUTH: "true"
            SOLR_SSL_CLIENT_KEY_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.keystore"
            SOLR_SSL_CLIENT_KEY_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_CLIENT_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_CLIENT_TRUST_STORE: "/opt/alfresco-search-services/keystore/ssl.repo.client.keystore"
            SOLR_SSL_CLIENT_TRUST_STORE_PASSWORD: "kT9X6oe68t"
            SOLR_SSL_CLIENT_TRUST_STORE_TYPE: "JCEKS"
            SOLR_OPTS: "
                -Dsolr.ssl.checkPeerName=false
                -Dsolr.allow.unsafe.resourceloading=true
            "
        ports:
            - 8084:8983
        volumes:
            - ./keystores/solr:/opt/alfresco-search-services/keystore

    share:
        build:
          context: ./share
          args:
            SHARE_TAG: ${SHARE_TAG}
        mem_limit: 1g
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -Xms500m
                -Xmx500m
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "

    postgres:
        image: postgres:${POSTGRES_TAG}
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    content-app:
        image: alfresco/alfresco-content-app:${ACA_TAG}
        mem_limit: 128m
        environment:
            BASEPATH: ./

    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        image: nginx:stable-alpine
        mem_limit: 128m
        depends_on:
            - alfresco
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd
        ports:
            - 8080:8080
        links:
            - alfresco
            - share
            - content-app
